export default {
  input: {
    type: 'input',
    label: '输入框',
    name: '',
    placeholder: '请输入...',
    required: false,
    readyonly: false,
    disabled: false,
    visible: true,
    desc: '提示信息',
    rules: [
      {
        required: false,
        message: '请正确输入',
        trigger: 'blur',
      },
    ],
  },
  textarea: {
    type: 'textarea',
    label: '文本域',
    name: '',
    placeholder: '请输入...',
    required: false,
    readyonly: false,
    disabled: false,
    visible: true,
    desc: '提示信息',
    rules: [
      {
        required: false,
        message: '请正确输入',
        trigger: 'blur',
      },
    ],
  },
  checkbox: {
    type: 'checkbox',
    label: '复选框',
    name: '',
    required: false,
    readyonly: false,
    disabled: false,
    visible: true,
    options: [],
    desc: '提示信息',
    rules: [
      {
        required: false,
        message: '至少选择一个',
      },
    ],
  },
  radio: {
    type: 'radio',
    label: '单选框',
    name: '',
    required: false,
    readyonly: false,
    disabled: false,
    visible: true,
    options: [],
    desc: '提示信息',
    rules: [
      {
        required: false,
        message: '请选择',
      },
    ],
  },
  select: {
    type: 'select',
    label: '下拉框',
    name: '',
    required: false,
    readyonly: false,
    disabled: false,
    visible: true,
    options: [],
    desc: '提示信息',
    rules: [
      {
        required: false,
        message: '请选择',
      },
    ],
  },
  date: {
    type: 'date',
    label: '日期',
    name: '',
    required: false,
    readyonly: false,
    disabled: false,
    visible: true,
    desc: '提示信息',
    showTime: false,
    format: 'yyyy-MM-dd',
    rules: [
      {
        required: false,
        message: '请选择日期',
      },
    ],
  },
  datetime: {
    type: 'date',
    label: '时间',
    name: '',
    required: false,
    readyonly: false,
    disabled: false,
    visible: true,
    desc: '提示信息',
    showTime: true,
    format: 'yyyy-MM-dd HH:mm',
    rules: [
      {
        required: false,
        message: '请选择时间',
      },
    ],
  },
  upload: {
    type: 'upload',
    label: '上传',
    name: '',
    required: false,
    readyonly: false,
    disabled: false,
    visible: true,
    btnText: '上传文件',
    fileType: 'image', // 'file'
    action: '',
    desc: '提示信息',
    rules: [
      {
        required: false,
        message: '请上传',
      },
    ],
  },
  rate: {
    type: 'rate',
    label: '评分',
    name: '',
    required: false,
    readyonly: false,
    disabled: false,
    visible: true,
    desc: '提示信息',
    rules: [
      {
        required: false,
        message: '请选择',
      },
    ],
  },
  desc: {
    type: 'desc',
    title: '标题',
    content: '段落描述信息',
    visible: true,
  },
};
